### ISSUE TITLE
Tailwind styles do not apply

### ISSUE THREAD

**Issue by codef0rmer** [ngneat/tailwind#65] opened 2021-01-30 07:09 UTC
I tried to setup this in a brand new Angular 10 application, however, the tailwind styles do not apply on any element no matter what I do.

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
</code></pre>

## Current behavior

1. Create a new Angular 10 Project over CLI `npx @angular/cli@10 new angular-tailwind`
2. Install Angular 10 specific package `ng add @ngneat/tailwind@5.2.4 `
    Note that it will still install v11 of custom-webpack builder. I changed it to 10.0.1 followed by `npm install`
3. Add `<button class="bg-green-500">Button</button>` in index.html
4. Run `npm run start` to notice that the styles are not applied.

## Expected behavior

The styles should have applied and the correct version of the custom-webpack builder should have been installed.

## Environment

<pre><code>
Angular version: 10.2.1

For Tooling issues:
- Node version: v10.17.0
- Platform: Mac OS Big Surr 11.1 (20C69)

**Comment by nartc** [comment] 2021-01-30 14:29
I was able to reproduce this. `patchPostCSS` does not seem to work with Angular 10. Thanks for reporting.

**Comment by nartc** [comment] 2021-01-30 16:21
Should be fixed with 5.2.5

**Closed by nartc** 2021-01-30 16:21 UTC
Labels: bug

**Comment by codef0rmer** [comment] 2021-01-30 17:27
Nice, thanks.

**Comment by codef0rmer** [comment] 2021-02-01 07:58
@nartc when v5.2.5 coming?

**Comment by beeman** [comment] 2021-02-01 08:14
> @nartc when v5.2.5 coming?

<img width="638" alt="image" src="https://user-images.githubusercontent.com/36491/106431572-76911600-643b-11eb-9630-d39e34533ca5.png">

It's already released!

You can install it by adding the version to the package name:

```
npm install @ngneat/tailwind@5.2.5
yarn add @ngneat/tailwind@5.2.5
```

**Comment by codef0rmer** [comment] 2021-02-02 10:02
Thanks @beeman. I could not find it in CHANGELOG hence asked. Nonetheless, worked just fine 👍

**Comment by nartc** [comment] 2021-02-02 12:38
@codef0rmer 5.2.5 is not in the changelog because I manually cut the release instead of using release-it. And I forgot to update the changelog.

**Comment by codef0rmer** [comment] 2021-02-02 18:53
Ah @nartc no worries. Thanks anyway, it's working just fine.
