### ISSUE TITLE
TypeError: getProcessedPlugins is not a function

### ISSUE THREAD

**Issue by bjornharvold** [ngneat/tailwind#76] opened 2021-02-12 09:22 UTC
## I'm submitting a...

<pre><code>
[X ] Bug report
</code></pre>

## Current behavior

I have a new NX Workspace and execute the 2 commands as described. The schematics work as they should. Then I try to run the project and it fails with this error:

```
Error: ./apps/customer/src/styles.scss
Module build failed (from ./node_modules/@angular-builders/custom-webpack/node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/@angular-builders/custom-webpack/node_modules/postcss-loader/dist/cjs.js):
TypeError: getProcessedPlugins is not a function
    at /Users/crash/git/trippay-spa/node_modules/tailwindcss/lib/processTailwindFeatures.js:75:83
    at LazyResult.runOnRoot (/Users/crash/git/trippay-spa/node_modules/@angular-builders/custom-webpack/node_modules/postcss/lib/lazy-result.js:303:16)
    at LazyResult.runAsync (/Users/crash/git/trippay-spa/node_modules/@angular-builders/custom-webpack/node_modules/postcss/lib/lazy-result.js:355:26)
    at async Object.loader (/Users/crash/git/trippay-spa/node_modules/@angular-builders/custom-webpack/node_modules/postcss-loader/dist/index.js:95:14)
    at /Users/crash/git/trippay-spa/node_modules/webpack/lib/NormalModule.js:316:20
    at /Users/crash/git/trippay-spa/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/crash/git/trippay-spa/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/crash/git/trippay-spa/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.loader (/Users/crash/git/trippay-spa/node_modules/@angular-builders/custom-webpack/node_modules/postcss-loader/dist/index.js:104:7)
``` 

I looked at TailwindCSS's issues and saw a similar error:
https://github.com/tailwindlabs/tailwindcss/issues/2810

## Expected behavior

Project should run with TailwindCSS installed. With Angular 11.2.0 supporting TailwindCSS out of the box, could that be why? NX Workspace v11.2.12 does not support TailwindCSS out of the box even though Angular 11.2.0 is installed. That's why I wanted to try if this schematic would make it work.

If I install a new Angular 11.2.0 project and add TailwindCSS, it works without a hitch. However, I cannot get it to work with Nx Workspace.

## Minimal reproduction of the problem with instructions

For bug reports please provide the _STEPS TO REPRODUCE_ and if possible a _MINIMAL DEMO_ of the problem

## Environment

<pre><code>
Angular version: 11.2.0
 
For Tooling issues:
- Node version: v12.20.1
- Platform:  Mac
</code></pre>

**Comment by TryHardDood** [comment] 2021-02-17 11:27
Possible duplicate of #67 

See fix [here](https://github.com/ngneat/tailwind/issues/67#issuecomment-775429597)

**Closed** 2021-03-09 17:45 UTC
