### ISSUE TITLE
Data path "" should NOT have additional properties(customWebpackConfig).

### ISSUE THREAD

**Issue by satish666** [ngneat/tailwind#55] opened 2021-01-20 19:42 UTC
After installation 
ng serve -o reflects 
```
Schema validation failed with the following errors:
  Data path "" should NOT have additional properties(customWebpackConfig).
```

**Comment by nartc** [comment] 2021-01-21 17:52
Do you use webpack 5 by any chance?

**Comment by mennomanschot** [comment] 2021-01-22 17:16
For what it's worth (I'm a relative newby to tailwind): I had the same error just now. It passed when I removed customWebpackConfig from architect.serve.options in angular.json. it is only referenced in build.options. Tailwind seems to be working fine.

**Comment by nartc** [comment] 2021-01-23 23:55
@mennomanschot Thanks for the info. However, that shouldn't be an issue since we're not adding `customWebpackConfig` to `serve` target. Check https://github.com/ngneat/tailwind/blob/20192d256e6817a20c14a9e0dad26a880891d680/libs/tailwind/src/utils/update-workspace-targets.ts#L21. We're only adding `customWebpackConfig` to `build` target.

@satish666 I'm not able to reproduce this issue. Are you able to provide a reproduce sample?

**Comment by AlexanderOpran** [comment] 2021-01-25 05:42
I have the same problem. I tried pretty much every possible solution to have tailwindcss 2.0 in my project with no avail. Here is the ngneat implementation (ngneat branch): https://github.com/AlexanderOpran/angular-tailwind-debug/tree/ngneat

**Comment by satish666** [comment] 2021-01-25 05:51
Hey I used 
"@angular-devkit/build-angular": "~0.1001.1",
and it worked . But it is not working with Angular 11 and "@angular-devkit/build-angular": "~0.1100.0",

**Comment by vltansky** [comment] 2021-01-25 08:20
@AlexanderOpran I got confused a bit - there is a problem in a branch you mentioned here.
Although PR that I created probably not relevant for you anymore. I'll put it here as an example:
https://github.com/AlexanderOpran/angular-tailwind-debug/pull/1

Error "Data path "" should NOT have additional properties(customWebpackConfig)." was due to `customWebpackConfig` in `serve` config:
https://github.com/AlexanderOpran/angular-tailwind-debug/pull/1/files#diff-2d2675bb4687601a5c7ccf707455132f90f3516a33716185687e5c41df59ac7dL176-L180

and using `@angular-builders/custom-webpack@10` instead of `v11`
https://github.com/AlexanderOpran/angular-tailwind-debug/pull/1/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L27-L28

`webpack.config.js` was outdated.

**Comment by nartc** [comment] 2021-01-25 14:32
@vltansky I’m confused. Why does “serve” has “customWebpackConfig” because ngneat/tailwind does not add it?

**Comment by vltansky** [comment] 2021-01-25 18:01
@nartc don't know it was already there. I guess just added manually by mistake.

**Comment by nartc** [comment] 2021-01-25 18:27
@vltansky I see. You have any action item to close this issue?

**Closed** 2021-01-26 14:46 UTC
Labels: question
